version: '3'
services:
  bot:
    build: ./
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bookworm
    environment:
      - POSTGRES_USER=inquisitor
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - inquisitor-postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  inquisitor-postgres-data:
    external: true
